### PR TITLE
v8 updates

### PR DESCRIPTION
**Pull request by roblarsen**

### CODE REVIEW

**Comment by coliff** [comment]
Looking good. We could update the version in package.json, but it's not really used for anything... maybe we could change it to 0.0.0 or 1.0.0 or something so we never need to change it again - or just update it to 8.0.0, I'm fine either way....

**Comment by roblarsen** [comment]
We use the version number to drive the links back to the released version on GitHub. I updated everything and added you to the maintainer line 👍 

This is ready to go.

**Comment by coliff** [comment]
Awesome. This PR doesn't include the build docs though, so we'll have to run the build script to update the `docs/` dir (where the site is hosted on GitHub Pages). Shall we do that on this PR?

**Comment by roblarsen** [comment]
I was in the middle of a push. The docs are included here as well.

**Pull request merged**
