### PR TITLE
Remove jshint

### LINKED ISSUE #185: replace jshint with eslint (to match github.com/h5bp/html5-boilerplate)
It'd be good to replace jshint with eslint to match the https://github.com/h5bp/html5-boilerplate repo.

### PR DESCRIPTION
**Pull request by roblarsen**
Closes #185

### CODE REVIEW

**Comment by coliff** [comment]
this looks good. I tested making a build with errors in the `src/main.js` file and the build still completed without any warnings. Ideally build should fail if JS test doesn't match the rules in: eslint-config-recommended

**Comment by coliff** [comment]
I think we could potentially remove the gulp-eslint dependency and just use eslint via a npm script.

**Review by coliff — CHANGES_REQUESTED** [review]
build is not failing on error (lint:js passes even if errors in the JS)

**Comment by roblarsen** [comment]
I got it to fail! Now let me fix the build and we'll be good to go. 

```
[20:53:25] 'lint:js' errored after 332 ms
[20:53:25] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 1 error
[20:53:25] 'build' errored after 335 ms
[20:53:25] ESLintError in plugin "run-sequence(lint:js)"
Error
    at finish (/workspaces/html5boilerplate.com/node_modules/run-sequence/index.js:82:12)
    at Gulp.onError (/workspaces/html5boilerplate.com/node_modules/run-sequence/index.js:93:3)
    at Gulp.emit (node:events:538:35)
    at Gulp.Orchestrator._emitTaskDone (/workspaces/html5boilerplate.com/node_modules/orchestrator/index.js:264:8)
    at /workspaces/html5boilerplate.com/node_modules/orchestrator/index.js:275:23
    at finish (/workspaces/html5boilerplate.com/node_modules/orchestrator/lib/runTask.js:21:8)
    at Transform.<anonymous> (/workspaces/html5boilerplate.com/node_modules/orchestrator/lib/runTask.js:52:4)
    at Transform.f (/workspaces/html5boilerplate.com/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at Transform.emit (node:events:538:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
[20:53:25] Finished 'clean:before' after 342 ms
@roblarsen ➜ /workspaces/html5boilerplate.com (eslint ✗) $ 
```

**Comment by roblarsen** [comment]
@coliff This errors on eslint failures and builds successfully now that I've cleaned up the script file. We should look at the actual JavaScript file to see what needs to be in there, still. Also, I don't know that I have access to the GA account, which is kind of funny. I'll reach out to Paul if I don't. We'll have to update.

**Comment by roblarsen** [comment]
(Rob ran off to check... he doesn't have access 🤣 ) dear @paulirish do you own the GA account for this site? Can you add me as an admin? Hope things are going well!

**Comment by coliff** [comment]
getting an error on `npm run build`

```sh
[13:23:17] 'build' errored after 1.3 s
[13:23:17] TypeError in plugin "run-sequence(generate:main.css)"
Message:
    Cannot read properties of undefined (reading 'close')
Stack:
TypeError: Cannot read properties of undefined (reading 'close')
    at Object.<anonymous> (C:\Users\coliff\Documents\GitHub\html5boilerplate.com\node_modules\postcss\node_modules\chalk\index.js:72:75)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\coliff\Documents\GitHub\html5boilerplate.com\node_modules\postcss\lib\css-syntax-error.js:8:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

**Comment by paulirish** [comment]
> (Rob ran off to check... he doesn't have access 🤣 ) dear @paulirish do you own the GA account for this site? Can you add me as an admin? Hope things are going well!

i added you as admin on mobile. it came through?

**Comment by roblarsen** [comment]
@paulirish Thanks! I just checked 5 minutes ago.

**Comment by roblarsen** [comment]
@coliff It seems like gulp-autoprefixer and  gulp-smoosher are weird with node 16. Running this against node 14 works. I pulled them out of this build and will address the functionality in the gulp upgrade PR. This should work, for now.

**Comment by roblarsen** [comment]
I merged this into the gulp upgrade branch

**Pull request closed without merging**
