### PR TITLE
Removes normalize

### LINKED ISSUE #369: Remove normalize CSS from homepage and from npm package (don't use it on the site)
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

### PR DESCRIPTION
**Pull request by roblarsen**
Plus other cleanup

closes #369

### CODE REVIEW

**Comment by coliff** [comment]
looks good so far - need to change this section though - and use a different/new icon.
image

**Comment by roblarsen** [comment]
I was going to do the content separately.

**Comment by roblarsen** [comment]
We should actually just have a main.css logo, I guess.

**Comment by roblarsen** [comment]
@coliff I put a placeholder file in there for now. Can you take a look, with the exception of the missing main.css logo and let me know how it looks? I can open an issue in main.css for a logo there

**Review by coliff — APPROVED** [review]

**Pull request merged**
