### PR TITLE
Removed twitter logo

### LINKED ISSUE #365: Update Twitter Icon X
### Prerequisites

- [X] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Proposal

Screenshot 2023-10-03 184942

### Motivation and context

The current Twitter icon in our application has been in use for quite some time, and we believe that an update is necessary to enhance the overall visual appeal and alignment with modern design trends. By refreshing the Twitter icon, we aim to provide users with a more contemporary and engaging experience.

### PR DESCRIPTION
**Pull request by Gowrish7**
## Types of changes

fixes #365
- [ ] Bug fix (non-breaking change which fixes an issue)
Removed the twitter logo in the footer
Thanks!
image

### CODE REVIEW

**Review by coliff — CHANGES_REQUESTED** [review]
- changes need to be made in the src/ directory and make a build to update docs/index.html
- Please remove twitter.svg image
- Remove the twitter card meta tags (not just comment them out)

**Comment by Gowrish7** [comment]
> * changes need to be made in the src/ directory and make a build to update docs/index.html
> * Please remove twitter.svg image
> * Remove the twitter card meta tags (not just comment them out)

Can you help me with first comment i am new to open source .

**Comment by coliff** [comment]
Hi. The details to make the build are in the README.

**Comment by Gowrish7** [comment]
> Hi. The details to make the build are in the README.

Hey coliff i have made npm run serve and this is the screen shot 
image

**Comment by Gowrish7** [comment]
@coliff  please check whether the changes done are proper and please do specify if anything went wrong

**Comment by coliff** [comment]
Changes must be made in the src/ directory. Your PR doesn't include changes to the index file in the src directory. Please update and squash your commits.

**Comment by pragyamishra56** [comment]
Screenshot 2023-10-04 130749

**Review by Gowrish7 — COMMENTED** [review]
i have done the changes in index.html in src directory

**Comment by pragyamishra56** [comment]
hey why have you done this I've been working on this issue

**Comment by Gowrish7** [comment]
> hey why have you done this I've been working on this issue

Hey @pragyamishra56  its not yet merged you can still submit your PR . I am just learning how to contribute.
Thanks

**Comment by coliff** [comment]
I appreciate the enthusiasm for contributing from you both. :-)

**Comment by pragyamishra56** [comment]
> Gowrish7

How is it possible you already created a PR 
Screenshot 2023-10-04 132449

**Comment by pragyamishra56** [comment]
> I appreciate the enthusiasm for contributing from you both. :-)

@coliff Could you kindly provide me guidance on How I request to pull the request so that I resolve it?

**Comment by Gowrish7** [comment]
> > I appreciate the enthusiasm for contributing from you both. :-)
> 
> @coliff Could you kindly provide me guidance on How I request to pull the request so that I resolve it?

Hey i have closed the PR

**Comment by Gowrish7** [comment]
> > I appreciate the enthusiasm for contributing from you both. :-)
> 
> @coliff Could you kindly provide me guidance on How I request to pull the request so that I resolve it?

@pragyamishra56 i guess you can make a seperate PR or should i close the PR ?

**Comment by pragyamishra56** [comment]
> > > I appreciate the enthusiasm for contributing from you both. :-)
> > 
> > 
> > @coliff Could you kindly provide me guidance on How I request to pull the request so that I resolve it?
> 
> @pragyamishra56 i guess you can make a seperate PR or should i close the PR ?

No need to close the PR. Good luck with your next contribution. Maybe that's why, so keep growing and contributing to open source!

**Comment by coliff** [comment]
Please- let's just get this finished and merged. Please remove the twitter.svg and rebuild. Then squash the commits. thanks.

**Comment by pragyamishra56** [comment]
> Please- let's just get this finished and merged. Please remove the twitter.svg and rebuild. Then squash the commits. thanks.

@coliff me or @Gowrish7

**Comment by coliff** [comment]
> > Please- let's just get this finished and merged. Please remove the twitter.svg and rebuild. Then squash the commits. thanks.
> 
> @coliff me or @Gowrish7

I really don't mind. Whoever can do it first.

**Comment by pragyamishra56** [comment]
can i do this ?

**Comment by coliff** [comment]
> can i do this ?

sure, if you want to make a new PR.

**Comment by roblarsen** [comment]
Hi @pragyamishra56 use this as an opportunity to learn about how open source works. There are plenty 

> can I do this? but how if he deletes his pr i can pull the request

Just create a new PR. This is a GREAT way to learn about how GitHub and open source works.  Consider that part homework to earn your Hacktoberfest t-shirt or whatever you're working towards.

**Comment by pragyamishra56** [comment]
> > > I appreciate the enthusiasm for contributing from you both. :-)
> > 
> > 
> > @coliff Could you kindly provide me guidance on How I request to pull the request so that I resolve it?
> 
> @pragyamishra56 I guess you can make a separate PR or should I close the PR?

If you don't mind can you close your PR

**Pull request closed without merging**
